const os = require("os")
console.log("Free Memory",os.freemem()/1024/1024/1024)
console.log("Total Memory",os.totalmem())
console.log("Version",os.version())
console.log("Processor",os.cpus())
console.log("Platform",os.platform())
console.log("Architecture",os.arch())
console.log("Type",os.type())
console.log("Release",os.release())
console.log("Cores",os.cpus().length)
console.log("CPU Speed",os.cpus()[0].speed)